### ISSUE TITLE
Not working with Jest

### ISSUE THREAD

**Issue by lmiller1990** [wonderful-panda/vue-tsx-support#16]
Hi,

I installed this using the vue cli plugin found [here](https://github.com/chanlito/vue-cli-plugin-tsx-support). Works great, except when running unit tests with Jest, I get this:

```
 FAIL  tests/unit/example.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/lachlanmiller/javascript/vue/tsx/src/components/HelloWorld.tsx:7
            return (<div>Ok</div>);
```

any ideas?

**Comment by wonderful-panda** [comment]
vue-tsx-support itself is tested by jest.

see package.json and files under test/jest as an example.

**Comment by lmiller1990** [comment]
Hey,

Thanks for the reply. I had a look, but I must be missing something. I was able to get it to work using `babel-jest` and `@babel/preset-typescript`. I also followed up here: https://github.com/vuejs/vue-cli/issues/3100. 

I'll close this for now, since it looks like it was something I was doing incorrectly. Thanks again, this library is excellent.
