### ISSUE TITLE
[bug] The dynamic element(tag) can not apply the onChange events to `on`.

### ISSUE THREAD

**Issue by snowyu** [wonderful-panda/vue-tsx-support#29]
like this:
```tsx
const Tag = this.props.long ? "textarea" : "input"

const input = <Tag 
  onChange={this.props.onChange}
  className="make-this-pretty"
  id="important-input"
/>;
```

**Comment by eshimischi** [comment]
`<input
      v-if="type !== 'textarea'"
      onChange={this.props.onChange}
      className="make-this-pretty"
      id="important-input"
/>
`

**Comment by snowyu** [comment]
I know you can use dynamic attribute.  But the question is for dynamic `element(tag)`, not attribute.

The `onChange` become to `attrs` when the tag is dynamic.

**Comment by snowyu** [comment]
sorry, I got the reason, stupid typo.

**Comment by eshimischi** [comment]
> I know you can use dynamic attribute. But the question is for dynamic `element(tag)`, not attribute.
> 
> The `onChange` become to `attrs` when the tag is dynamic.

```
<input
      v-if="type !== 'textarea'"
      ref="input"
      :type="newType"
      :name="name"
      :placeholder="placeholder"
      :maxlength="maxlength"
      :value="computedValue"
      v-bind="$attrs"
...
/>

export default {
  inheritAttrs: false,
  props: {}
}
```

**Comment by chanlito** [comment]
Does `component` work here?🤔

**Comment by snowyu** [comment]
Yes, in fact it's not here, it should be in https://github.com/vuejs/jsx/tree/master/packages/babel-plugin-transform-vue-jsx/ . 

Here just is tsx syntax checker. I've just found it.

jsx is still not very useful for complex component, such as: https://github.com/snowyu/qinputex

**Comment by mesqueeb** [comment]
@snowyu also see this answer: https://github.com/vuejs/jsx/issues/104#issuecomment-578669982

very helpful!
