### ISSUE TITLE
It is possible to use this with vue-class-component?

### ISSUE THREAD

**Issue by nullptr128** [wonderful-panda/vue-tsx-support#3]
Hello!

I've playing around your library and I am wondering if it is possible to use this with vue-class-component for better typechecking inside component code?

**Comment by wonderful-panda** [comment]
see https://github.com/wonderful-panda/vue-tsx-support#component-1

Or [vue-typed-component](https://github.com/wonderful-panda/vue-typed-component)
(vue-typed-component wraps vue-class-component and components written by this are tsx-ready by default)

**Comment by chanlito** [comment]
@wonderful-panda 👏👏what you have done here is amazing. Thank you. The vue community need better tsx support.
