### ISSUE TITLE
Convertion does not work properly

### ISSUE THREAD

**Issue by eakarpov** [wonderful-panda/vue-tsx-support#32]
```typescript
        const ToolbarTyped = tsx.ofType<{ tools: ITool[] }>().convert(Toolbar);
        return (
            <div>
                <ToolbarTyped tools={this.tools} />
            </div>);
```

Error:(34, 18) TS2322: Type '{ tools: ITool[]; }' is not assignable to type 'ComponentOptions<{ _tsxattrs: TsxComponentAttrs<{ tools: ITool[]; }, {}, {}>; } & Toolbar, DefaultData<{ _tsxattrs: TsxComponentAttrs<{ tools: ITool[]; }, {}, {}>; } & Toolbar>, DefaultMethods<{ _tsxattrs: TsxComponentAttrs<...>; } & Toolbar>, DefaultComputed, PropsDefinition<...>, Record<...>>'.
  Property 'tools' does not exist on type 'ComponentOptions<{ _tsxattrs: TsxComponentAttrs<{ tools: ITool[]; }, {}, {}>; } & Toolbar, DefaultData<{ _tsxattrs: TsxComponentAttrs<{ tools: ITool[]; }, {}, {}>; } & Toolbar>, DefaultMethods<{ _tsxattrs: TsxComponentAttrs<...>; } & Toolbar>, DefaultComputed, PropsDefinition<...>, Record<...>>'.

**Comment by eshimischi** [comment]
> ```ts
> ```ts
>         const ToolbarTyped = tsx.ofType<{ tools: ITool[] }>().convert(Toolbar);
>         return (
>             <div>
>                 <ToolbarTyped tools={this.tools} />
>             </div>);
> ```
> 
> 
> Error:(34, 18) TS2322: Type '{ tools: ITool[]; }' is not assignable to type 'ComponentOptions<{ _tsxattrs: TsxComponentAttrs<{ tools: ITool[]; }, {}, {}>; } & Toolbar, DefaultData<{ _tsxattrs: TsxComponentAttrs<{ tools: ITool[]; }, {}, {}>; } & Toolbar>, DefaultMethods<{ _tsxattrs: TsxComponentAttrs<...>; } & Toolbar>, DefaultComputed, PropsDefinition<...>, Record<...>>'.
> Property 'tools' does not exist on type 'ComponentOptions<{ _tsxattrs: TsxComponentAttrs<{ tools: ITool[]; }, {}, {}>; } & Toolbar, DefaultData<{ _tsxattrs: TsxComponentAttrs<{ tools: ITool[]; }, {}, {}>; } & Toolbar>, DefaultMethods<{ _tsxattrs: TsxComponentAttrs<...>; } & Toolbar>, DefaultComputed, PropsDefinition<...>, Record<...>>'.
> ```

{ tools: ITool[] } не может быть ITool[], доступны только стандартные типы string | number | boolean или перечисления строк "red" | "green" | blue

**Comment by wonderful-panda** [comment]
@eakarpov 
can you show me type of `Toolbar` ?

I guess `Toolbar` is ComponentOptions itself (like ```{ props: {...}, computed: {...} }```)
`convert()` only accepts Vue constructor for now. (like ```Vue.extend({ props: {...}, ... })```)

This workaround should work

```typescript
const ToolbarTyped = tsx.ofType<{ tools: ITool[] }>().convert(Vue.extend(Toolbar));
// or
const ToolbarTyped = tsx.ofType<{ tools: ITool[] }>().convert(Toolbar as any as typeof Vue);
```

**Comment by eakarpov** [comment]
@wonderful-panda I fixed the problem by changing tsx-shims.d.ts file as yours in this repository. Toolbar is an instance of VueConstructor, so it suits the convert method.

**Comment by wonderful-panda** [comment]
@eakarpov 
Does original `tsx-shims.d.ts` come from vue-cli ? (I'm not so familiar to vue-cli)
If yes, I'll add this problem as FAQ to README.

**Comment by eakarpov** [comment]
@wonderful-panda Yes, the original one was generated by vue-cli.

**Comment by wonderful-panda** [comment]
@eakarpov Thank you
