### ISSUE TITLE
Requires migration documentation

### ISSUE THREAD

**Issue by Shinigami92** [wonderful-panda/vue-tsx-support#33]
It would be nice if we can open a wiki or something to help for migration process.

I just had a problem with `onClick`. After some time, I noticed that I had to use `onClick={() => this.close()}` instead of `onClick={this.close()}`.
This was a dialog and I could not open it because it was closed automatically every time I wanted to open it.

**Comment by wonderful-panda** [comment]
`vue-tsx-support` is just a type checker, not transpiler.

I think the right place to report this issue is https://github.com/vuejs/jsx
