### ISSUE TITLE
How to use `v-model` modifiers?

### ISSUE THREAD

**Issue by Shinigami92** [wonderful-panda/vue-tsx-support#34]
Docs: https://vuejs.org/v2/guide/forms.html#Modifiers

How can we use something like this:
```<input v-model.number="age" type="number">```

**Comment by wonderful-panda** [comment]
see https://github.com/vuejs/jsx#directives

FYI, camelCase style (`vModel`, `vModel_number`, etc) causes compilation error.
You can avoid error with using snake-case (`v-model`, `v-model_number`, etc)

**Comment by Shinigami92** [comment]
Thanks, `v-model_number` works perfectly
