### ISSUE TITLE
span 标签上添加class 一直类型错误，求大神指点

### ISSUE THREAD

**Issue by chuanweiDOU** [wonderful-panda/vue-tsx-support#43]
Type '{ children: string; class: string; onClick: (event: any) => void; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLSpanElement>, HTMLSpanElement>'.
  Property 'class' does not exist on type 'DetailedHTMLProps<HTMLAttributes<HTMLSpanElement>, HTMLSpanElement>'.
    14 |     },
    15 |     render(): VNode {
  > 16 |         return <span class={ this.className } onClick={this.onClick}>{this.text}</span>;
       |                 ^
    17 |     }
    18 | });

**Comment by wonderful-panda** [comment]
`DetailedHTMLProps` maybe comes from react.

Check your `package.json` and remove react or libraries depend on react from dependencies.
