### ISSUE TITLE
Intellisense support in code editors (e.g. VS Code)

### ISSUE THREAD

**Issue by vjcagay** [wonderful-panda/vue-tsx-support#47]
When I am typing TSX code on my editor the html tags does not have any kind of intellisense. They are set as `any` for some reason. Is this my fault or `vue-tsx-support` does not have this feature yet?

TypeScript 3.6.4

<img width="407" alt="Screen Shot 2019-11-06 at 14 45 22" src="https://user-images.githubusercontent.com/3283683/68271546-35794d00-00a4-11ea-9d5a-5fc8b64253bd.png">
<img width="521" alt="Screen Shot 2019-11-06 at 14 45 47" src="https://user-images.githubusercontent.com/3283683/68271554-37dba700-00a4-11ea-8f05-3de46114cb91.png">

**Comment by wonderful-panda** [comment]
![image](https://user-images.githubusercontent.com/1205852/68370628-4a2b1300-0180-11ea-8c69-a11c957a0837.png)

It should work. Probably there is something wrong in your environment.

Can you show me example project which this problem can be reproduced ?

**Comment by vjcagay** [comment]
Never mind, I got it to work now. Thanks!
