### ISSUE TITLE
v-for doesn't work

### ISSUE THREAD

**Issue by mesqueeb** [wonderful-panda/vue-tsx-support#50]
When I tried this:

```html
<MyComponent v-for={row in this.rows} key={row.name} />
```
I get this error: 
> Cannot find name 'row'

**Comment by numfin** [comment]
[yourarray].map(value => <MyComponent key={value.name} />

**Comment by mesqueeb** [comment]
Thanks !!! I had to take a crash course JSX and TSX 😉 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
