### ISSUE TITLE
sync modifier or listening for `:update` event

### ISSUE THREAD

**Issue by mesqueeb** [wonderful-panda/vue-tsx-support#51]
How can I do either:

```html
<MyComponent mode.sync={mode} />
```
or
```html
<MyComponent mode={mode} on[mode:update]={val => this.mode = val} />
```

**Comment by numfin** [comment]
<MyComponent mode={mode} onModeUpdate={fn}

**Comment by mesqueeb** [comment]
Thanks !!! I'll try this tomorrow!!! 😉 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
@numfin it didn't work.

I can catch the event in the Vue dev tools:
<img width="239" alt="image" src="https://user-images.githubusercontent.com/3253920/71649451-41a32300-2d52-11ea-8f51-d58987ac94e8.png">

But even though I added this to my TSX template:
```
onUpdateMode={(val: string) => (this.mode = val)}
```
nothing happened

**Comment by mesqueeb** [comment]
This worked:
```
on={{'update:mode': () => ()}}
```
