### ISSUE TITLE
computed props can't be cross-referenced

### ISSUE THREAD

**Issue by mesqueeb** [wonderful-panda/vue-tsx-support#52]
<img width="832" alt="Screenshot 2020-01-22 at 16 23 13" src="https://user-images.githubusercontent.com/3253920/72873585-83146600-3d33-11ea-86a1-bf9abac1dffc.png">

it says my computed prop called `props` doesn't exist, while it's right there.

**Comment by wonderful-panda** [comment]
You should annotate return type on each computed, methods and render() explicitly.

For more detail, see https://vuejs.org/v2/guide/typescript.html#Annotating-Return-Types
