### ISSUE TITLE
request: improve sync modifier

### ISSUE THREAD

**Issue by mesqueeb** [wonderful-panda/vue-tsx-support#53]
I do this on almost all of my components:
```js
<MyComponent
  mode={this.mode}
  on={{'update:mode': (val: string) => (this.mode = val)}}
/>
```
it could be greatly improved if the sync modifier syntax was available:
```js
<MyComponent
  mode.sync={this.mode}
/>
```

Is it possible to add this feature to vue-tsx-support?

**Comment by eshimischi** [comment]
https://github.com/wonderful-panda/babel-plugin-vue-jsx-modifier
