### ISSUE TITLE
JSX element type '~~' does not have any construct or call signatures.

### ISSUE THREAD

**Issue by mesqueeb** [wonderful-panda/vue-tsx-support#54]
Hi!
I have an error I can't seem to solve. I'd love some help! 😎 
```ts
const PhaseComponent = getComponentOfPhase(phase)
const phaseComponent = <PhaseComponent {...{ props: phaseComponentProps }} />
```

getComponentOfPhase returns this:
<img width="672" alt="image" src="https://user-images.githubusercontent.com/3253920/73177074-5d32fb00-4151-11ea-9423-41e44b9cf9c1.png">

PhaseComponent shows this:
<img width="788" alt="image" src="https://user-images.githubusercontent.com/3253920/73177095-6ae88080-4151-11ea-946a-2da8ff755763.png">

the full **getComponentOfPhase** looks something like this, a "index.tsx" file that just returns the appropriate component based on a condition:
<img width="724" alt="image" src="https://user-images.githubusercontent.com/3253920/73177186-ad11c200-4151-11ea-88d4-33adf7db1ca3.png">

**Comment by wonderful-panda** [comment]
You should annotate return type explicitly.

```typescript
// You can specify type of props instead of `{}` if all component accepts same props.
export function getComponentOfPhase(phase: LessonPhaseInfo): tsx.TsxComponent<Vue, {}> {
    ...
}
```

**Comment by mesqueeb** [comment]
The problem with that is that it loses type information on **which props** I can use.

Each component I'm returning in the switch have different props typings.

**Comment by wonderful-panda** [comment]
As error message said, JSX component must be class or function, union types are not allowed.
