### ISSUE TITLE
Support for conditional directives. v-if, v-else, v-else-if

### ISSUE THREAD

**Issue by vvolfster** [wonderful-panda/vue-tsx-support#60]
Would like to thank your efforts for creating this package. It has made our project and vue components quite typesafe and we are very happy with it. The only thing missing for me is conditional directives. I know we can use ternary statements in the render() function but to me the conditional directives are great for reducing code clutter.

I have worked a bunch in react land and am using this babel plugin: https://github.com/peakchen90/babel-plugin-react-directives

I am wondering if this plugin could perhaps be integrated into the vue-tsx-support library or something similar.

Would be happy to give it a try myself and make a PR if I knew where to start.

**Comment by mesqueeb** [comment]
+1 !!

**Comment by wonderful-panda** [comment]
It is not scope of vue-tsx-support.

I guess https://github.com/vuejs/jsx is the right place of this issue.
