### ISSUE TITLE
Native event listeners

### ISSUE THREAD

**Issue by Song-Qian** [wonderful-panda/vue-tsx-support#62]
Hello, I have a question in using vue-tsx-support. When I write a component, I need to complete an api function in a vue.
<input ...$listeners ></input>
I was browsing the vue-tsx-support development documentation and found that it can be used
<Component {...{ nativeOn: {click: ...}}} />
So I changed the code to
<input type='text' value={ me.value} onInput={ (e) => me.$emit('input', e.target.value)} {...{ nativeOn: {...me .$listeners}} }></input>
But webpack has an error. Should I use this syntax, should I still need the relevant dependencies?
![image](https://user-images.githubusercontent.com/33682535/84853302-74876c00-b091-11ea-9f7c-3d0a43e36c6a.png)

**Comment by wonderful-panda** [comment]
Some mistakes exist in your code.

1. `input` is not a component, so you can't use `nativeOn`, use `on` instead.

   ```typescript
   <input {...{ on: this.$listener }} />
   ```

2. In JSX, input tag must be closed.
https://stackoverflow.com/questions/30852751/expected-corresponding-jsx-closing-tag-for-input-reactjs

But these maybe not the reason of this error.
It seems your babel configuration is something wrong.
