### ISSUE TITLE
when v3 stable will be released ? and the road map to finish it

### ISSUE THREAD

**Issue by nour-dev** [wonderful-panda/vue-tsx-support#69]
is there any missing features from the current work to make v3 stable ?
any road map to finish it ?

**Comment by wonderful-panda** [comment]
I'm waiting for this.
https://github.com/vuejs/jsx/pull/142

**Comment by nour-dev** [comment]
@wonderful-panda the referenced pull request was merged . any other thing needed to make v 3 stable or at least rc ?

**Comment by wonderful-panda** [comment]
3.0.2 released.

**Comment by nour-dev** [comment]
@wonderful-panda thank you for the wonderful package.
