### ISSUE TITLE
`onInput` event type of input elements is incorrect

### ISSUE THREAD

**Issue by libre-man** [wonderful-panda/vue-tsx-support#74]
When using the `onInput` event type on a `input` element the value of `event.target.value` is `string | string[] | undefined`, however it seems that the html specification says that the `value` attribute of an `input` element can only be `string`. This issues seems to be cause by https://github.com/wonderful-panda/vue-tsx-support/blob/master/types/dom.d.ts#L193 which I think should be `value: string;`.

**Comment by wonderful-panda** [comment]
3.2.0-beta.1 maybe solve this problem
