### ISSUE TITLE
Missing attribute of `file` in InputHTMLAttributes

### ISSUE THREAD

**Issue by keyakko** [wonderful-panda/vue-tsx-support#79]
A type error occurs when using an Input element with the attribute `type="file"`.

I wrote tsx codes like below.
<img width="564" alt="Screen Shot 2021-04-25 at 11 11 41" src="https://user-images.githubusercontent.com/25705297/115978063-16cc8600-a5b8-11eb-8a6b-46d85cdb3450.png">

When I retrieve a file, it cannot be retrieved properly due to a type error.
<img width="777" alt="Screen Shot 2021-04-25 at 11 13 45" src="https://user-images.githubusercontent.com/25705297/115978085-2fd53700-a5b8-11eb-86ae-2d13646764ac.png">

In this case, `event.target` will contain `HTMLInputElement`.
And `HTMLInputElement.files` is expected to be undefined(optional) or FileList.
https://html.spec.whatwg.org/multipage/input.html#htmlinputelement
> attribute FileList? files;

**Comment by wonderful-panda** [comment]
Try 3.2.0-beta.1
