### ISSUE TITLE
Mixin function is not exported but mentioned in the doc.

### ISSUE THREAD

**Issue by chanlito** [wonderful-panda/vue-tsx-support#9]
![image](https://user-images.githubusercontent.com/15667259/45300818-91485480-b539-11e8-900d-fcc82a0b79e2.png)

I had to use the following way.

```ts
const Flex = componentFactory.mixin(textXsCenterMixin).create({
```

**Comment by eshimischi** [comment]
Look to the right Example: https://github.com/wonderful-panda/vue-tsx-support#mixin

**Comment by chanlito** [comment]
![image](https://user-images.githubusercontent.com/15667259/45308934-cca04e80-b54c-11e8-9a94-08d09051ccd0.png)

[ts] Property 'mixin' does not exist on type

**Comment by eshimischi** [comment]
@chanlito 

check your package.json 

`"devDependencies": {
...
"vue-tsx-support": "^2.1.1",
...
}`

**Comment by wonderful-panda** [comment]
@chanlito This is intentional. Document is wrong.
`tsx.mixin(...)` is confusing (It seems to be a function which returns a mixin object, not a factory).

I'll fix document and consider exposing `mixin` with some other name
